version: "3.9"

services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      MONGO_URI: "mongodb://mongo:27017"
      QDRANT_HOST: "qdrant"
      QDRANT_PORT: "6333"
      REDIS_HOST: "redis"
    depends_on:
      - kafka
      - mongo
      - qdrant
      - redis
    volumes:
      - ../:/workspace
    networks:
      - sentencify-net

  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_NODE_ID: "1"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9094"
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,PLAINTEXT_HOST://:9093,CONTROLLER://:9094"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
    volumes:
      - kafka-data:/bitnami/kafka
    networks:
      - sentencify-net

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - sentencify-net

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - sentencify-net

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - sentencify-net

networks:
  sentencify-net:
    driver: bridge

volumes:
  kafka-data:
  mongo-data:
  qdrant-data:
